name: CI for OrangeHRM

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 0 * * *'  # Запуск кожного дня о півночі

jobs:
  test:
    runs-on: windows-latest
    env:
      ENV: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Playwright install
        run: |
          playwright install

      - name: Run tests
        run: |
          pytest -m "smoke" -v --disable-warnings